### ISSUE TITLE
Support for community-based policy expressions in ARTEMIS conf

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#178]
**Is your feature request related to a problem? Please describe.**
Capability for network operator to annotate hijack alerts according to their severity, based on combinations of BGP communities present in the hijack BGP updates. Note that this issue is only about the conf syntax; the conf file sections containing this new input will be then parsed and used to check BGP updates against them in the detection stage (separate issue, TBD). Afterwards, the detection should annotate alerts with the relevant characterization (e.g., critical, medium, low) (separate issue, TBD).

**Describe the solution you'd like**
```
- prefixes:
    - *my_prefix_list
  origin_asns:
    - *my_asn_list
  neighbors:
    - *my_neighbor_list
  policies:
    - 'no-export'    
  communities:
        'critical': '<and/or operation on BGP communities>' 
        'medium': '<and/or operation on BGP communities>' 
        'low': '<and/or operation on BGP communities>' 
  mitigation: manual
```
The 
```
<and/or operation on BGP communities> 
```
should be sth like a string of format:
```
(1234:4567 and 2345:72893) or 5627:17217
```
which can be applied on the set of BGP communities present in the hijack BGP update path(s).
If the expressions hold, the appropriate severity level annotates the alert (and logger): these will be handled in separate issues (TBD).

Proposed format in detail (example):
```
'communities':
      'critical': 
       - 'and': 
           - X:Y
           - Z:W
       - 'or':
          - 'and':
              - A:B
              - !C:D # ! means not
        ...
```
This can be translated to a dict as follows:
```
{
  "communities": {
    "critical": [
      {
        "and": [
          "X:Y", 
          "Z:W"
        ]
      }, 
      {
        "or": [
          {
            "and": [
              "A:B", 
              "!C:D"
            ]
          }
        ]
      }
    ]
  }
}
```

and should be parsed as:
```
(X:Y AND Z:W) OR (A:B AND (NOT C:D))
``` 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
