### ISSUE TITLE
Feature request:  Slack "block" formatting

### ISSUE THREAD

**Issue by smith8917** [FORTH-ICS-INSPIRE/artemis#218]
Slack is moving toward a JSON "block" approach for formatting messages.  More information can be found here:  https://api.slack.com/messaging/composing/layouts

Could this formatting be integrated into the backend logging.yaml setup?  

To give you an idea of what it looks like in action, I pasted an example layout below that I created on: https://api.slack.com/tools/block-kit-builder
`
[
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": "*ARTEMIS has detected a configured prefix (8.23.153.0/24) being hijacked*"
		}
	},
	{
		"type": "divider"
	},
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": "Hijacked prefix: 8.23.153.0/24\nHijacking AS: 46435\nTime Started: 2019-08-19 12:43:54\ntype: E|0|-|-\nURL: https://artemis.exampledomain.com/main/hijack?key=1bbbaffff5a7bc3b2c56e69c7bf7790b16"
		}
	}
]
`

**Comment by slowr** [comment]
Hey, thanks for sharing information about the slack's layout.
I will add this feature for the next milestone and if anyone is interested contributing the changes through a PR it's welcome.

**Comment by smith8917** [comment]
Thanks for the update, @slowr

**Comment by smith8917** [comment]
at @slowr 's recommendation, I added a formatter (and attempted to add the requisite square brackets) without any luck:

        format: '{"type": "section","text": {"type": "mrkdwn","text": "%(message)s"}}'

The message came through as-is instead of formatted.  

If it's possible to break apart the "message" and choose the KVPs that will be sent from the logger/formatter to Slack, that would be ideal.  I've attached two screenshots of how this would look with formatted Slack integration and without. 

![Screen Shot 2019-09-06 at 4 51 59 PM](https://user-images.githubusercontent.com/48694749/64466801-bb8b0e80-d0c8-11e9-9b4d-5c18c101357d.png)
![Screen Shot 2019-09-06 at 4 51 49 PM](https://user-images.githubusercontent.com/48694749/64466808-bf1e9580-d0c8-11e9-963b-f6c0e2b60788.png)

**Comment by vkotronis** [comment]
@smith8917 I tried the following in logging.yaml and seems to work fine:
```
formatters:
    ...
    custom_slack_formatter:
        format: '{"type": "section","text": {"type": "mrkdwn","text": "%(message)s"}}'
    ...
```
and:
```
handlers:
   ...
    hijack_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: custom_slack_formatter
        filename: /var/log/artemis/hijack.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
    ...
```
and:
```
loggers:
   ...
   loggers:
        hijack_logger:
            level: INFO
            handlers: [hijack_file_handler]
            propagate: no
```
and it seems to work fine:
```
{"type": "section","text": {"type": "mrkdwn","text": "{
    "asns_inf": [
        5408,
        33891,
        21320,
        6762,
        2603,
        47692,
        57111,
        174,
        37271
    ],
    "community_annotation": "NA",
    "configured_prefix": "139.91.0.0/16",
    "hijack_as": 8522,
    "key": "4893da626bbd22d5485054f64d834ff3",
    "monitor_keys": [
        "46af9aa4ab52726076f1e30d2c6caa8b"
    ],
    "peers_seen": [
        47692,
        57111,
        37271
    ],
    "prefix": "139.91.0.0/16",
    "time_detected": 1568211056.7694154,
    "time_last": 1568210813.0,
    "time_started": 1568207623.0,
    "timestamp_of_config": 1568211044.4426441,
    "type": "E|0|-|-"
}"}}
```
So the message comes out formatted. Could you please re-check?
I will also look if there can be some custom formatting for specific fields for the json; however the basic format should work.

**Comment by vkotronis** [comment]
@smith8917 I tried with slack and it works fine, using a sample configuration:
```
version: 1
disable_existing_loggers: True
formatters:
    ...
    custom_slack_formatter:
        format: '[{"type": "section","text": {"type": "mrkdwn","text": "%(message)s"}}]'

handlers:
    ...
    # for slack
    slack_handler:
        class: slacker_log_handler.SlackerLogHandler
        api_key: "my_legacy_slack_api_token"
        channel: "#test_slack_formatting"
        username: "Hijack Announcer"
        level: INFO
    ...

loggers:
    ...
    hijack_logger:
        level: INFO
        handlers: [slack_handler]
        propagate: no
    ...

root:
    level: INFO
    handlers: []
```
![Screenshot from 2019-09-11 18-04-20](https://user-images.githubusercontent.com/1815007/64709399-d8578580-d4be-11e9-9c5a-2834f2afa1b1.png)

**Comment by vkotronis** [comment]
@smith8917 so the first part of the issue (that the message came through as-is instead of formatted) should be addressed with this, please double-check. I am checking whether the slack log handler can also provide the ability to break apart the message with logging.yaml primitives.

**Comment by vkotronis** [comment]
a no you are right when I add the custom formatter
```
slack_handler:
    class: slacker_log_handler.SlackerLogHandler
    formatter: custom_slack_formatter
    api_key: SLACK_API_TOKEN
    channel: "#general"
    username: "Hijack Announcer"
    level: INFO
```
the issue remains.
