### ISSUE TITLE
Env variable/configuration and functionality to translate exaBGP/hist feed from local RCs into configuration

### ISSUE THREAD

**Issue by vkotronis** [FORTH-ICS-INSPIRE/artemis#253]
**Is your feature request related to a problem? Please describe.**
This is in the context of auto-config. Instead of using polling approaches (like Ansible) or requiring agent-based mechanisms (like Puppet), use instead the direct feed (BGP updates) from the local routers/RCs and translate it into configuration. Same should be able to work for historical feeds.

**Describe the solution you'd like**
Option in .env (False by default) to use local monitors (IPs and ports need to be defined) to translate their feeds into configuration. Check the current learning approach we adopt when the user presses 'ignore+learn" on a new alert; we can similarly build the configuration automatically based on the received feed.

**Comment by vkotronis** [comment]
Also maybe it would be nicer to have a flag in exaBGP monitor conf section like: "use this monitor for building the conf file". Will think about this and start with this feature. Cool stuff!

**Comment by vkotronis** [comment]
How to get the neighbors assuming that we get only prefix originations in exaBGP? I propose that we use communities, such as follows:
```
prefix: P
as-path: <legal_origin>
communities: <legal_origin>:<first_neighbor>, ..., <legal_origin>:<second_neighbor>
```
Will need the user to extend route maps to append the expanded peer-group per prefix origination in the BGP updates sent to ARTEMIS via exaBGP. Need to get feedback from operators on this.

**Comment by vkotronis** [comment]
Example:
configuration file before:
```
#
# ARTEMIS Configuration File (Bootstraping)
#
# Start of Prefix Definitions
prefixes:
  # bootstrap prefix
  bootstrap_prefix: &bootstrap_prefix 0.0.0.0/0
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
    bgpstreamhist:
        dir: "/root/test_updates/"
        autoconf: "true"
# End of Monitor Definitions

# Start of ASN Definitions
asns:
  bootstrap_asn: &bootstrap_asn 1
# End of ASN Definitions

# Start of Rule Definitions
rules:
  - prefixes:
    - *bootstrap_prefix
    origin_asns:
    - '*'
# End of Rule Definitions
```

configuration file after a single update
```
10.0.0.0/16|1|1|1|mon-project-1|mon-group-1|A|"[{""asn"":1, ""value"":2},{""asn"":1, ""value"":3}]"|1571184001
```
```
#
# ARTEMIS Configuration File (Bootstraping)
#
# Start of Prefix Definitions
prefixes:
  # bootstrap prefix
  bootstrap_prefix: &bootstrap_prefix 0.0.0.0/0
  AUTOCONF_P_10_0_0_0_16: &AUTOCONF_P_10_0_0_0_16
  - 10.0.0.0/16
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
  bgpstreamhist:
    dir: "/root/test_updates/"
    autoconf: "true"
# End of Monitor Definitions

# Start of ASN Definitions
asns:
  bootstrap_asn: &bootstrap_asn 1
  AUTOCONF_AS_1: &AUTOCONF_AS_1
  - 1
  AUTOCONF_AS_2: &AUTOCONF_AS_2
  - 2
  AUTOCONF_AS_3: &AUTOCONF_AS_3
  - 3
# End of ASN Definitions

# Start of Rule Definitions
rules:
- prefixes:
  - *bootstrap_prefix
  origin_asns:
  - '*'
# End of Rule Definitions
- prefixes:
  - *AUTOCONF_P_10_0_0_0_16
  origin_asns:
  - *AUTOCONF_AS_1
  neighbors:
  - *AUTOCONF_AS_2
  - *AUTOCONF_AS_3
  mitigation: manual
```
This works in the current PR for updates (not integrated).

**Comment by vkotronis** [comment]
Actually the simplest config to begin with should be:
```
#
# ARTEMIS Configuration File (Bootstraping)
#
# Start of Prefix Definitions
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
    bgpstreamhist:
        dir: "/root/test_updates/"
        autoconf: "true"
# End of Monitor Definitions

# Start of ASN Definitions
# End of ASN Definitions

# Start of Rule Definitions'
# End of Rule Definitions
```

The bootstrap prefix should be "hidden", only the autoconf monitors should "see" it

**Comment by vkotronis** [comment]
Note that we can also bootstrap using exabgp, as follows:
```
#
# ARTEMIS Configuration File (Bootstraping)
#
# Start of Prefix Definitions
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
    exabgp:
    - ip: ...
      port: ...
      autoconf: "true"
# End of Monitor Definitions

# Start of ASN Definitions
# End of ASN Definitions

# Start of Rule Definitions
# End of Rule Definitions
```
