### ISSUE TITLE
Overruling rules (AS announcements)

### ISSUE THREAD

**Issue by marcgweg** [FORTH-ICS-INSPIRE/artemis#288]
**Describe the bug**
I have a list of prefixes with the same origin AS. I want to create two rulesets:
1) prefixlist with origin AS and a select set of neighbors;
2) prefixlist with origin AS and an other select list of neighbors for which a no_export is required.
Aspected behaviour is that both use-cases is respected.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
In config.yaml I have the following setup:
prefixes:
  simple_prefix_list: &my_prefixes
  - 192.168.78.0/24
  - 192.168.10.0/24
<... skip monitors ...>
asns:
  my_asn: &my_asn
  1
  my_neighbors: &myneighbors
  - 11
  - 12
  my_neighbors: &my_noexp_neighbors
  - 21
  - 222
rules:
- prefixes:
  - *my_prefixes
  origin_asns:
  - *my_asn
  neighbors:
  - *my_neighbors
  mitigation: manual
- prefixes:
  - *my_prefixes
  origin_asns:
  - *my_asn
  neighbors:
  - *my_noexp_neighbors
  policies:
  - 'no-export'
  mitigation: manual

**Expected behavior**
Both situation will be observed in their respective situation (is the combination origin AS and neighbour with given policy).
Now only the no-export rule is followed.

**Screenshots**

**System (please complete the following information):**
 - Version latest

**Additional context**

**Comment by vkotronis** [comment]
@marcgweg thank you for reporting this Marc. Could you please elaborate more on the issue, so that we can add respective tests and see what is going on? I.e., do you actually see BGP updates within `*my_prefixes` with origin `*my_asn` and neighbor within `myneighbors` and only the second rule kicks in? Could you also please fix the typo in `my_neighbors`? It seems that you use exactly the same name for 2 different sets (the normal and the no export ones) and the yaml anchors seem also mistyped: `&myneighbors` (instead of `&my_neighbors`). This does not generate an error in yaml but may cause this logical problem with the 2 rules. After this is fixed, could you try again and let us know? if it is still an issue I will add more tests to check what is going on. Thanks!

**Comment by vkotronis** [comment]
To help clarify my previous comment, please try the following conf:
```
simple_prefix_list: &my_prefixes
    - 192.168.78.0/24
    - 192.168.10.0/24
    <... skip monitors ...>
    asns:
    my_asn: &my_asn
    1
    my_neighbors: &my_neighbors
    - 11
    - 12
    my_noexp_neighbors: &my_noexp_neighbors
    - 21
    - 222
    rules:
    prefixes:
        *my_prefixes
        origin_asns:
        *my_asn
        neighbors:
        *my_neighbors
        mitigation: manual
    prefixes:
        *my_prefixes
        origin_asns:
        *my_asn
        neighbors:
        *my_noexp_neighbors
        policies:
        'no-export'
        mitigation: manual
```
(with the mentioned typos fixed). If the problem persists, please let me know.

**Comment by marcgweg** [comment]
Okay, I use a different config in production, then I sent to you. In your config I miss the "-" symbols. I check my config, and try to get results you asked for.

**Comment by marcgweg** [comment]
I guess the following was wrongly typed:
my_noexp_neighbors: &my_noexp_neighbors should be
my_neighbors: &my_noexp_neighbors !?

**Comment by slowr** [comment]
@marcgweg the names you specify the AS groups and prefixes (my_asn, my_neighbors, etc) are like variables so they need to be unique. For your example this is the correct configuration:
```
prefixes:
    simple_prefix_list: &simple_prefix_list
        - 192.168.78.0/24
        - 192.168.10.0/24

<... skip monitors ...>

asns:
    my_asn: &my_asn
        8522
    my_neighbors_1: &my_neighbors_1
        - 11
        - 12
    my_neighbors_2: &my_neighbors_2
        - 21
        - 22

rules:
- prefixes:
    - *simple_prefix_list
  origin_asns:
    - *my_asn
  neighbors:
    - *my_neighbors_1
  mitigation:
      manual
- prefixes:
    - *simple_prefix_list
  origin_asns:
    - *my_asn
  neighbors:
    - *my_neighbors_2
  policies:
     'no-export'
  mitigation:
     manual
```
