### ISSUE TITLE
AS Path pre-pending sequence

### ISSUE THREAD

**Issue by sward1557** [FORTH-ICS-INSPIRE/artemis#443]
**Is your feature request related to a problem? Please describe.**
We leverage addition ASes in our prepend to do traffic engineering and need a way to monitor this sequence after the origin AS upto and including our peering AS since they are separate ASes.

**Describe the solution you'd like**
As discussed with Artemis engineering team we need an additional config parameter that will take in this sequence of ASes from an exaBGP session and a detector that will monitor for manipulation of that AS sequence.  Examples included in additional context.

**Describe alternatives you've considered**
The only other alternative that isn't really acceptable is to ignore the AS sequence between the origin AS and peer AS.

**Additional context**
Example of advertisements:
```
  Prefix                AS path
* 22.16.196.0/23        209 227 227 227 227 227 227 11164 11166 1112 I
* 22.48.176.0/20        209 227 11164 117 1111 2277 I
* 22.51.64.0/19          209 227 11164 2298 I
* 22.51.65.0/24          209 227 2298 I
* 22.64.4.0/24            209 227 227 227 227 227 227 11164 11165 117 1111 1114 1225 I
* 99.56.0.0/16            209 227 11164 117 115 116 2232 I
```
Break out example of advertisement:
```
Prefix: 22.16.196.0/23
Origin AS: 1112
Peer AS: 227
Neighbor AS: 209
Prepend AS sequence: 227 227 227 227 227 227 11164 11166 1112
(The prepend sequence doesn't need to include origin AS since the detector already looks like it)

Prefix: 22.48.176.0/20
Origin AS: 2277
Peer AS: 227
Neighbor AS: 209
Prepend AS sequence: 227 11164 117 1111 2277 

Prefix: 22.51.64.0/19
Origin AS: 2298
Peer AS: 227
Neighbor AS: 209
Prepend AS sequence: 227 11164 2298 

Prefix: 22.51.65.0/24
Origin AS: 2298
Peer AS: 227
Neighbor AS: 209
Prepend AS sequence: NONE 

Prefix: 22.64.4.0/24 
Origin AS: 1225
Peer AS: 227
Neighbor AS: 209
Prepend AS sequence: 227 227 227 227 227 227 11164 11165 117 1111 1114 1225

Prefix: 99.56.0.0/16 
Origin AS: 1225
Peer AS: 227
Neighbor AS: 209
Prepend AS sequence: 227 11164 117 115 116 2232 
```
This might be what the config file rule looks like:
```
- prefixes:
  - *99_56_0_0_16
  origin_asns:
  - *2232_asn 
  neighbors:
  - *209_asn 
  peer_asn:
  - *227_asn 
  prepend_seq
  - *116_asn 
  - *115_asn 
  - *117_asn 
  - *11164_asn  
  mitigation: manual
(I'm not sure how to include the Peer AS since it is not the same an the Origin AS. Also the Peer AS might repeat and we should keep track of the repeating ASes in the sequence)
```

FYI there are example where there in nothing in the prepend sequence and the solution would need to allow for that.

**Comment by slowr** [comment]
We talked with the team and we came up with a solution for your use cases. For performance reasons we decided that if possible the neighbor AS and peer AS should be inside the prepend sequence (neighbor+peer+sequence). So the configuration would look like this:
```
- prefixes:
  - *99_56_0_0_16
  origin_asns:
  - *2232_asn 
  prepend_seq: 
  - [209,227,116,115,117,11164]
  - .. (if multiple prepends are possible)
  mitigation: manual
```
So the idea is that we will get the rules based on the `origin_asn` and then start trying to match the prepend sequences.
What do you think @sward1557 ?
