### ISSUE TITLE
Changes in configuration have non-deterministic effect

### ISSUE THREAD

**Issue by leopoul** [FORTH-ICS-INSPIRE/artemis#610]
**Describe the bug**
Config changes to cause pseudo-hijacks make BGP updates appear as hijacks even when origin AS is restored to the legitimate one. The provided config is an example with prefixes from Google, Cloudflare, Neustar, etc. The bug has been triggered with different combinations of prefixes/ASes not only the ones used in this report.

**Affected Component(s)**
- [X] Back-End (Database, Microservices, Containers, etc)
- [ ] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**To Reproduce**
1. On a clean instance of Artemis apply the initial configuration as shown below. It expected to cause hijack detection due to ASNs being deliberately mis-typed.
Start Artemis as:
`docker-compose up -d --scale prefixtree=4 --scale database=4 --scale detection=4`

Configuration:
```
# Start of Prefix Definition
prefixes:
  target_prefixes: &target_prefixes
  - 2001:4860:4805::/48
  - 2606:4700:4700::/48
  - 2001:4860::/32
  - 1.1.1.0/24
  - 8.8.8.0/24
  - 64.6.64.0/24

asns:
  origin_asns: &origin_asns
  - 10512
  - 13336
  - 15167
  - 43516

# End of ASN Definitions
monitors:
  riperis: ['']
  bgpstreamkafka:
    host: stream.routeviews.org
    port: 9092
    topic: '^routeviews.*\.bmp_raw'
# End of Monitor Definition
# Start of Rule Definition
rules:

- prefixes:
  - *target_prefixes
  origin_asns:
  - *origin_asns

```
2. Let BGP updates flow for some time. Make sure there are hijacks detected for v4 and v6 prefixes for the same AS - see Screenshot 1.
3. Start fixing mistypes ASes in config. Start with `AS13336`. Switch it to `13335` and monitor. It is expected that existing hijacks will be marked as outdated. Config now should be:
```
# Start of Prefix Definition
prefixes:
  target_prefixes: &target_prefixes
  - 2001:4860:4805::/48
  - 2606:4700:4700::/48
  - 2001:4860::/32
  - 1.1.1.0/24
  - 8.8.8.0/24
  - 64.6.64.0/24

asns:
  origin_asns: &origin_asns
  - 10512
  - 13335
  - 15167
  - 43516

# End of ASN Definitions
monitors:
  riperis: ['']
  bgpstreamkafka:
    host: stream.routeviews.org
    port: 9092
    topic: '^routeviews.*\.bmp_raw'
# End of Monitor Definition
# Start of Rule Definition
rules:

- prefixes:
  - *target_prefixes
  origin_asns:
  - *origin_asns
```
4. Check Hijacks tab. While initial hijacks for `13336` have been marked as outdated, there are plenty new updates marked as hijacks for `13335`. See Screenshots 2 and 3.
5. There are also some weird hijack IDs, as if multiple hijack IDs are assigned to a single update. See Screenshot 4.
76 Wait for some minutes, in my case 10mins or so and watch for BGP updates. Some BGP updates from `1.1.1.0/24` appear as non-hijacks, others appear as hijacks. See Screenshot 5.

**Attempts to fix**
1. Because prefixtree microservice seems to be responsible for translating the config into an object that is then attached to each BGP update, try to restart prefixtree so that a refresh of state is forced:
```
docker-compose restart prefixtree
Restarting artemis_prefixtree_1 ... done
Restarting artemis_prefixtree_3 ... done
Restarting artemis_prefixtree_2 ... done
Restarting artemis_prefixtree_4 ... done
```
No effect.

2. Bring all microservices down and restart them: 
```
docker-compose down && docker-compose up -d --scale prefixtree=4 --scale database=4 --scale detection=4
```
Wait for some time and check hijacks page. There are still hijacks which are considered as ongoing. See Screenshot 6.

**Expected behavior**
Changes in configuration should be reflected in BGP updates wrt hijack detection.

**Screenshots**
![image](https://user-images.githubusercontent.com/770064/133974679-db3ba8b2-4a7a-4405-976a-11b0b21b8be3.png)
Screenshot 1.

![image](https://user-images.githubusercontent.com/770064/133975235-92a6a797-9822-4f66-8fd9-84799fd7c500.png)
Screenshot 2.

![image](https://user-images.githubusercontent.com/770064/133975310-0e0de765-036a-4bd0-a9ef-a62967893bb9.png)
Screenshot 3.

![image](https://user-images.githubusercontent.com/770064/133975379-968f0871-7e91-4aef-81cf-f1b23958feab.png)
Screenshot 4.

![image](https://user-images.githubusercontent.com/770064/133976695-e33cd787-c9d7-4ffe-a235-484cf8e6e36c.png)
Screenshot 5.

![image](https://user-images.githubusercontent.com/770064/133978034-22b5620a-026e-4137-ace2-f32c2a403848.png)
Screenshot 6.

**System (please complete the following information):**
 - OS: [CentOS Linux release 8.3.2011]
 - Browser [N/A happens with all browsers]
 - Version [latest at the moment of filling the issue]

**Additional context**
