### ISSUE TITLE
IPv6 prefix that is defined for transit is reported as E1 hijack.

### ISSUE THREAD

**Issue by stkonst** [FORTH-ICS-INSPIRE/artemis#611]
Hi guys,

We have an IPv6 prefix that is defined in the configuration of Artemis:
```
prefixes:

# NL PREFIXES

  super_prefix_NL: &super_prefix_NL
  - 2001:67c:1a8::/48
  ```

And we have the transit provider defined few lines later
```
asns:
# NL ASNs
  my_asn_NL: &my_asn_NL 1200
  primary_upstream_NL_3: &primary_upstream_NL_3 4455
```

In the rule section we "glue" the prefixes with the transit provider:
```
rules:
# NL RULES
# These are the rules for the upstream providers of AS1200
- prefixes:
  - *super_prefix_NL
  origin_asns:
  - *my_asn_NL
  neighbors:
  - *primary_upstream_NL_3
  mitigation: manual
  ```

But still Artemis reports the prefix as being hijacked from AS4455 with E1 type but that's not correct as 4455 is a true transit provider of us.
