### ISSUE TITLE
No Mail sending 

### ISSUE THREAD

**Issue by sonnenteich** [FORTH-ICS-INSPIRE/artemis#624]
**Describe the bug**
I configured the setting to get an alert via email, but when I achieve a hijacking I get no notification.
How can I debug this process? 

**Affected Component(s)**
- [x] Back-End (Database, Microservices, Containers, etc)
- [x] Front-End (Flask, API, etc)
- [ ] Docs
- [ ] Build System

**Expected behavior**
I exact to get a email. 

**Additional context**
I run Artemis in a local kubernetes instance.

**Comment by vkotronis** [comment]
Hello @sonnenteich ! We would need a snippet of the configuration you are using to help you debug. Could you share a sample file with the sensitive information (passwords, host info, etc.) filtered out? The dcumentation on this is here: https://bgpartemis.readthedocs.io/en/latest/loggingconf/

Typically the errors done by users in this context are:
1. Malformed yaml
2. Forgetting to attach their mail handler to the mail logger

It also may be sth `k8s`-specific with network connectivity, but let's rule out the other factors first.

**Comment by sonnenteich** [comment]
Hey, @vkotronis thanks for your answer. 
The mail part of my loggingconf looks like this:
```
# for email
smtps_handler:
    # artemis_utils.logaux.TLSSMTPHandler for TLS
    # artemis_utils.logaux.SSLSMTPHandler for SSL
    class: artemis_utils.logaux.TLSSMTPHandler
    level: INFO
    formatter: simple
    mailhost:
    - mail.host.com
    - 25
    fromaddr: from@email.com
    toaddrs:
    - to1@email.com
    - to2@email.com
    subject: "Artemis BGP-HIJACK Warning"
    credentials:
    # - username
    # - pass
    secure: False
```
I have a further question, which services should be triggered to send an email, I cant see anything in the logs.
