### ISSUE TITLE
Don't load config file or modulies

### ISSUE THREAD

**Issue by Sivolen** [FORTH-ICS-INSPIRE/artemis#626]
After starting via docker, all modules are launched, the web interface opens, but it is empty and if you look at the config in the web interface, it does not see it.
```
 docker-compose up -d
Creating redis    ... done
Creating rabbitmq  ... done
Creating postgres ... done
Creating mongodb   ... done
Creating postgrest            ... done
Creating graphql              ... done
Creating artemis_notifier_1   ... done
Creating artemis_prefixtree_1 ... done
Creating artemis_prefixtree_2 ... done
Creating artemis_prefixtree_3 ... done
Creating artemis_prefixtree_4 ... done
Creating artemis_database_1   ... done
Creating artemis_database_2   ... done
Creating artemis_database_3   ... done
Creating artemis_database_4   ... done
Creating artemis_mitigation_1        ... done
Creating artemis_riperistap_1        ... done
Creating artemis_detection_1         ... done
Creating artemis_detection_2         ... done
Creating artemis_detection_3         ... done
Creating artemis_detection_4         ... done
Creating pg-amqp-bridge              ... done
Creating artemis_autoignore_1        ... done
Creating artemis_exabgptap_1         ... done
Creating frontend                    ... done
Creating artemis_bgpstreamhisttap_1  ... done
Creating artemis_bgpstreamlivetap_1  ... done
Creating artemis_bgpstreamkafkatap_1 ... done
Creating artemis_configuration_1     ... done
Creating nginx                       ... done
Creating artemis_fileobserver_1      ... done
Creating artemis_autostarter_1       ... done
```

**Screenshots**
in atach

**System (please complete the following information):**
 - OS: [ubuntu 20.04]
 - Browser [firefox]
 - Version 98.0.2 ]

**Additional context**
my config

```
#
# ARTEMIS Configuration File (FORTH NETWORK)
#
# Start of Prefix Definitions
prefixes:
  pso_prefix1: &pso_prefix1
  - 91.212.81.0/24
  pso_prefix2: &pso_prefix2
  - 212.6.30.0/24
# End of Prefix Definitions

# Start of Monitor Definitions
monitors:
  riperis: ['']
  #bgpstreamlive:
  #- routeviews
  #- ris
  #- caida
  # exabgp:
  # - ip: 192.168.1.1
  #   port: 5000
  # - ip: 192.168.5.1
  #   port: 5000
  #bgpstreamhist: "/root/23_7_2019_csvs"
  bgpstreamkafka:
    host: stream.routeviews.org
    port: 9092
    topic: '^routeviews.*\.bmp_raw'
# End of Monitor Definitions
# Start of ASN Definitions
asns:
  pso_asn: &pso_asn
  - 196721
  mts_asn: &mts_asn
  - 8359
  solnce_asn: &Solnce
  - 51004
# End of ASN Definitions

# Start of Rule Definitions
rules:

- prefixes:
  - *pso_prefix1
  - *pso_prefix2
  origin_asns:
  - *pao_asn
  neighbors:
  - *mts_asn
  - *solnce_asn
  mitigation: manual

- prefixes:
  - *pso_prefix2
  origin_asns:
  - *pso_asn
  neighbors:
  - *mts_asn
  - *solnce_asn
  mitigation: manual
# End of Rule Definitions
```
![error1](https://user-images.githubusercontent.com/7619656/162100098-c59ec945-a126-460e-9dc3-2dbcfb52f396.png)
![error2](https://user-images.githubusercontent.com/7619656/162100110-bffbcecc-e90a-49c1-9208-c209f82d9f93.png)
