### ISSUE TITLE
Writing Hijacks to SYSLOG to be consumed by Splunk (etc)

### ISSUE THREAD

**Issue by chewsterB** [FORTH-ICS-INSPIRE/artemis#661]
**We want to get HIJACK logs into other systems**

We have configured Artemis and are successfully monitoring hijacks (using ASN 12654).

We have configured the logging in both Backend and Monitor (with detached config files) as follows:

```
    syslog_handler:
        class: logging.handlers.SysLogHandler
        level: DEBUG
        formatter: simple
        address: ['IP of underlying dockerhost', 514]

loggers:
    artemis_logger:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler, syslog_handler]
        propagate: no
    mail_logger:
        level: INFO
        handlers: [syslog_handler]
        propagate: yes
    hijack_logger:
        level: INFO
        handlers: [syslog_handler]
        propagate: yes

```

There is logging from docker arriving at rsyslog - but we don't see any hijacks or any status changes to hijacks (e.g. acknowledged, resolved).

Either a) we have a config error elsewhere - in which case your guidance would be appreciated
or
b) Please can we have logging of hijacks and status changes, sent to syslog (the documentation seems to indicate that this should work)

Many thanks!
